#!/bin/sh

MYHOST=$( hostname -s )
DST_DIR="/tmp/check_mirror/${MYHOST}"

[ -d "${DST_DIR}" ] && rm -rf "${DST_DIR}"
[ -r /tmp/iso-images.conf ] && rm -f /tmp/iso-images.conf
[ ! -d "${DST_DIR}" ] && mkdir -p ${DST_DIR}

# //check_iso валидирует доступность ресурсов и генерирует отчет в check_mirror
#SOURCE="cloud"
SOURCE="iso"

SKIP_CLOUD=" \
alpine3 \
dynfi4_ufs \
freefire14_ufs \
oyos \
windows10_ru \
"

SKIP_ISO=" \
alpine3 \
dynfi4_ufs \
freefire14_ufs \
oyos \
windows10_ru \
"

SKIP_PROFILES="
vm-freebsd-helloSystem-x64.conf \
"

TMP_CBSD_CHECKISO_CONF="/root/myb-build/myb-extras/bin/cbsd_checkiso.conf"
TMP_CBSD_API_CLOUD_IMAGES_JSON="/root/myb-build/myb-extras/cbsd_api_cloud_images.json"
TMP_CBSD_BHYVE_API_CONF="/root/myb-build/myb-extras/bin/bhyve-api.conf"

DYN_FILES=$( find /root/myb-build/myb-extras/bin/ -type f -exec grep -l "# auto-generated by gen-myb-data.sh" {} \; )

for i in ${DYN_FILES}; do
	echo "purge ${i}"
#	rm -f ${i}
done

#exit 0

gen_checkiso_conf()
{
	local i=
	jname="${1}"

	conf=
	eval conf="\$image_${jname}"

	if [ ! -r "${conf}" ]; then
		echo "no such: ${conf}"
		return 1
	fi

	echo ${conf}

	fetch=
	iso_site=
	cbsd_iso_mirrors=
	iso_img=
	iso_img_dist=
	register_iso_name=
	register_iso_as=

	. ${conf}

	if [ "${fetch}" != "1" ]; then
		echo "fetch disabled: ${conf}"
		return 1
	fi

	iso_mirrors_count=0
	for i in ${iso_site}; do
		echo "${i}"
		iso_mirrors_count=$(( iso_mirrors_count + 1 ))
	done

	cbsd_mirrors_count=0
	for i in ${cbsd_iso_mirrors}; do
		echo "${i}"
		cbsd_mirrors_count=$(( cbsd_mirrors_count + 1 ))
	done

	echo "ISO mirrors count: ${iso_mirrors_count}"
	echo "CBSD mirrors count: ${cbsd_mirrors_count}"

	if [ -n "${iso_img_dist}" ]; then
		iso_img="${iso_img_dist}"
	fi
	echo "${iso_img}"
	echo "${register_iso_name}"

	res="${jname}_iso=\"\${workdir}/src/iso/${register_iso_name}\""

	echo "${res}" >> ${TMP_CBSD_CHECKISO_CONF}
	return 0
}


check_mirror()
{
	local conf="${1}" i=
	echo "* ${conf}"

	local _profile_name=$( basename ${conf} )


	fetch=
	iso_site=
	cbsd_iso_mirrors=
	iso_img=
	iso_img_dist=
	register_iso_name=
	register_iso_as=

	if [ ! -r "${conf}" ]; then
		echo "not found: ${conf}"
		return 1
	fi
	. ${conf}

	if [ "${fetch}" != "1" ]; then
		echo "fetch disabled: ${conf}"
		return 1
	fi

	iso_mirrors_count=0
	for i in ${iso_site}; do
		echo "${i}"
		iso_mirrors_count=$(( iso_mirrors_count + 1 ))
	done

	cbsd_mirrors_count=0
	for i in ${cbsd_iso_mirrors}; do
		echo "${i}"
		cbsd_mirrors_count=$(( cbsd_mirrors_count + 1 ))
	done

	echo "ISO mirrors count: ${iso_mirrors_count}"
	echo "CBSD mirrors count: ${cbsd_mirrors_count}"
	echo "Orig size, bytes: [${iso_img_dist_size}]"

	notes=
	if [ ${iso_mirrors_count} -lt 2 ]; then
		_normal=$(( 10 - iso_mirrors_count ))
		notes="mirrors too small: add ${_normal}"
	elif [ ${iso_mirrors_count} -gt 10 ]; then
		_normal=$(( iso_mirrors_count - 10 ))
		notes="mirrors too lot: ${iso_mirrors_count}: remove ${_normal} "
	fi

	for i in ${iso_site}; do
		if [ -n "${iso_img_dist}" ]; then
			_src_file="${i}${iso_img_dist}"
		else
			_src_file="${i}${iso_img}"
		fi
		printf "  * Check: ${_src_file}"
		res_ok=1
		headers=$( curl --connect-timeout 20 -s -I --follow "${_src_file}" )
		status=$(echo "${headers}" | grep -i '^HTTP/' | tail -n1 | awk '{print $2}')
		content_length=$( echo "${headers}" | grep -i '^Content-Length' | tail -n1 | awk '{print $2}' | tr -d ';\r\n' )

		if [ "${status}" -eq 200 ]; then
			printf ", [file exist] "
			if [ -n "${content_length}" ]; then
				printf ", size: [${content_length}] bytes"
				if [ "${content_length}" != "${iso_img_dist_size}" ]; then
					printf ", size wrong"
					res_ok=0
				fi
			else
				res_ok=0
				printf ", size unknown"
			fi
		else
			res_ok=0
			printf ", [not found]. HTTP-status: ${status}"
		fi
		echo
		echo "Valid: ${res_ok}"
		echo

		if [ ${res_ok} -ne 1 ]; then
			[ ! -d ${DST_DIR}/${_profile_name} ] && mkdir -p ${DST_DIR}/${_profile_name}
			echo "${_src_file}" >> ${DST_DIR}/${_profile_name}/bad.txt
		fi
	done

	if [ -n "${notes}" ]; then
		echo "${_profile_name}: ${notes}" > ${DST_DIR}/${_profile_name}.notes
	fi
}

# support for override by arg, e.g:
# ./init.sh /usr/local/cbsd/etc/defaults/vm-freebsd-FreeBSD-aarch64-14.3.conf
if [ -n "${1}" ]; then
	echo "full_list=\"$*\"" > /tmp/iso-images.conf
fi


## MAIN
if [ ! -r /tmp/${SOURCE}-images.conf ]; then

	truncate -s0 /tmp/${SOURCE}-images.conf
	full_list=

	env NOCOLOR=1 cbsd get-profiles src=${SOURCE} | grep -v "^VM_PROFILE" | awk '{printf $1" "$2"\n"}' | while read _p _t; do

		if [ "${SOURCE}" = "cloud" ]; then
			myb_image=
			if [ ! -r /usr/local/cbsd/etc/defaults/vm-${_t}-${_p}.conf ]; then
				echo "no such /usr/local/cbsd/etc/defaults/vm-${_t}-${_p}.conf" 1>&2
				continue
			fi

			. /usr/local/cbsd/etc/defaults/vm-${_t}-${_p}.conf > /dev/null 2>&1

			if [ -z "${myb_image}" ]; then
				echo "no such myb_image for: /usr/local/cbsd/etc/defaults/vm-${_t}-${_p}.conf" 1>&2
				continue
			fi

			for i in ${SKIP_CLOUD} ${SKIP_ISO}; do
				[ "${i}" = "${myb_image}" ] && continue 2
			done

			echo "image_${myb_image}=\"/usr/local/cbsd/etc/defaults/vm-${_t}-${_p}.conf\"" >> /tmp/${SOURCE}-images.conf

			if [ -z "${full_list}" ]; then
				full_list="${myb_image}"
			else
				full_list="${full_list} ${myb_image}"
			fi
			sysrc -qf /tmp/${SOURCE}-images.conf full_list="${full_list}"
		else
			if [ -z "${full_list}" ]; then
				full_list="/usr/local/cbsd/etc/defaults/vm-${_t}-${_p}.conf"
			else
				full_list="${full_list} /usr/local/cbsd/etc/defaults/vm-${_t}-${_p}.conf"
			fi
			sysrc -qf /tmp/${SOURCE}-images.conf full_list="${full_list}"
		fi
	done
else
	. /tmp/${SOURCE}-images.conf
fi

. /tmp/${SOURCE}-images.conf

echo "FULL: ${full_list}"
# ISO ONLY
for i in ${full_list}; do
	echo "check_mirror \"${i}\""
	check_mirror "${i}"
done

exit 0

xfull_list=

truncate -s0 ${TMP_CBSD_CHECKISO_CONF}

xfull_list_cnt=0

[ -d ${DST_DIR} ] && rm -rf ${DST_DIR}
mkdir -p ${DST_DIR}

for i in ${full_list}; do
	if ! gen_checkiso_conf "${i}"; then
		continue
	fi

	if [ -z "${xfull_list}" ]; then
		xfull_list="${i}"
	else
		xfull_list="${xfull_list} ${i}"
	fi

	xfull_list_cnt=$(( xfull_list_cnt + 1 ))

done

echo "jail_iso=\"\${workdir}/basejail/base_amd64_amd64_\${ver}/bin/sh\"" >> ${TMP_CBSD_CHECKISO_CONF}
echo >> ${TMP_CBSD_CHECKISO_CONF}
echo "check=\"${xfull_list}\"" >> ${TMP_CBSD_CHECKISO_CONF}

truncate -s0 ${TMP_CBSD_API_CLOUD_IMAGES_JSON} ${TMP_CBSD_BHYVE_API_CONF}

cat >>${TMP_CBSD_API_CLOUD_IMAGES_JSON}<<EOF
{
  "images": [
EOF

_cnt=0

for i in ${full_list}; do

	vm_os_type=
	vm_profile=
	ci_user_add=
	conf=
	eval conf="\$image_${i}"
	. ${conf}

	_cnt=$(( _cnt + 1 ))
	if [ ${_cnt} -ne ${xfull_list_cnt} ]; then
		_res="    \"${i}\","
	else
		_res="    \"${i}\""
	fi
	echo "${_res}" >> ${TMP_CBSD_API_CLOUD_IMAGES_JSON}

	cat >>${TMP_CBSD_BHYVE_API_CONF}<<_______EOF
${i}_vm_os_type="${vm_os_type}"
${i}_vm_os_profile="${vm_profile}"
${i}_ssh_user="${ci_user_add}"

_______EOF

	cat > /root/myb-build/myb-extras/bin/${i}<<_______EOF
#!/bin/sh
# auto-generated by gen-myb-data.sh
profile="vm-${vm_os_type}-${vm_profile}.conf"
cbsd fetch_iso path="/usr/jails/etc/defaults/\${profile}" conv2zvol=1 keepname=0 dstdir=default fastscan=1 cloud=1
/root/bin/checkiso.sh check
exit 0
_______EOF
	chmod +x /root/myb-build/myb-extras/bin/${i}
done

cat >>${TMP_CBSD_API_CLOUD_IMAGES_JSON}<<EOF
  ]
}
EOF
